// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/v1/annotations.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service-level annotations
type ServiceDescriptor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PossibleErrorCodes []string               `protobuf:"bytes,1,rep,name=possible_error_codes,json=possibleErrorCodes,proto3" json:"possible_error_codes,omitempty"`
	CommonErrorCodes   []string               `protobuf:"bytes,2,rep,name=common_error_codes,json=commonErrorCodes,proto3" json:"common_error_codes,omitempty"`
	ErrorExamples      []*ErrorExample        `protobuf:"bytes,3,rep,name=error_examples,json=errorExamples,proto3" json:"error_examples,omitempty"`
	PathPrefixes       []*PathPrefix          `protobuf:"bytes,4,rep,name=path_prefixes,json=pathPrefixes,proto3" json:"path_prefixes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceDescriptor) Reset() {
	*x = ServiceDescriptor{}
	mi := &file_core_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDescriptor) ProtoMessage() {}

func (x *ServiceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDescriptor.ProtoReflect.Descriptor instead.
func (*ServiceDescriptor) Descriptor() ([]byte, []int) {
	return file_core_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceDescriptor) GetPossibleErrorCodes() []string {
	if x != nil {
		return x.PossibleErrorCodes
	}
	return nil
}

func (x *ServiceDescriptor) GetCommonErrorCodes() []string {
	if x != nil {
		return x.CommonErrorCodes
	}
	return nil
}

func (x *ServiceDescriptor) GetErrorExamples() []*ErrorExample {
	if x != nil {
		return x.ErrorExamples
	}
	return nil
}

func (x *ServiceDescriptor) GetPathPrefixes() []*PathPrefix {
	if x != nil {
		return x.PathPrefixes
	}
	return nil
}

type ErrorExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorDetail           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorExample) Reset() {
	*x = ErrorExample{}
	mi := &file_core_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorExample) ProtoMessage() {}

func (x *ErrorExample) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorExample.ProtoReflect.Descriptor instead.
func (*ErrorExample) Descriptor() ([]byte, []int) {
	return file_core_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorExample) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcCode      int32                  `protobuf:"varint,1,opt,name=grpc_code,json=grpcCode,proto3" json:"grpc_code,omitempty"`
	Details       []*ErrorDetailInfo     `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_core_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_core_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetGrpcCode() int32 {
	if x != nil {
		return x.GrpcCode
	}
	return 0
}

func (x *ErrorDetail) GetDetails() []*ErrorDetailInfo {
	if x != nil {
		return x.Details
	}
	return nil
}

type ErrorDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *ErrorInfo             `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetailInfo) Reset() {
	*x = ErrorDetailInfo{}
	mi := &file_core_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailInfo) ProtoMessage() {}

func (x *ErrorDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailInfo.ProtoReflect.Descriptor instead.
func (*ErrorDetailInfo) Descriptor() ([]byte, []int) {
	return file_core_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetailInfo) GetDetail() *ErrorInfo {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_core_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_core_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PathPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathPrefix) Reset() {
	*x = PathPrefix{}
	mi := &file_core_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathPrefix) ProtoMessage() {}

func (x *PathPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathPrefix.ProtoReflect.Descriptor instead.
func (*PathPrefix) Descriptor() ([]byte, []int) {
	return file_core_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *PathPrefix) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_core_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceDescriptor)(nil),
		Field:         50001,
		Name:          "core.v1.service_descriptor",
		Tag:           "bytes,50001,opt,name=service_descriptor",
		Filename:      "core/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "core.v1.method_descriptor",
		Tag:           "bytes,50002,opt,name=method_descriptor",
		Filename:      "core/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "core.v1.message_descriptor",
		Tag:           "bytes,50003,opt,name=message_descriptor",
		Filename:      "core/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "core.v1.field_descriptor",
		Tag:           "bytes,50004,opt,name=field_descriptor",
		Filename:      "core/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional core.v1.ServiceDescriptor service_descriptor = 50001;
	E_ServiceDescriptor = &file_core_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string method_descriptor = 50002;
	E_MethodDescriptor = &file_core_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string message_descriptor = 50003;
	E_MessageDescriptor = &file_core_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string field_descriptor = 50004;
	E_FieldDescriptor = &file_core_v1_annotations_proto_extTypes[3]
)

var File_core_v1_annotations_proto protoreflect.FileDescriptor

const file_core_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x19core/v1/annotations.proto\x12\acore.v1\x1a google/protobuf/descriptor.proto\"\xeb\x01\n" +
	"\x11ServiceDescriptor\x120\n" +
	"\x14possible_error_codes\x18\x01 \x03(\tR\x12possibleErrorCodes\x12,\n" +
	"\x12common_error_codes\x18\x02 \x03(\tR\x10commonErrorCodes\x12<\n" +
	"\x0eerror_examples\x18\x03 \x03(\v2\x15.core.v1.ErrorExampleR\rerrorExamples\x128\n" +
	"\rpath_prefixes\x18\x04 \x03(\v2\x13.core.v1.PathPrefixR\fpathPrefixes\":\n" +
	"\fErrorExample\x12*\n" +
	"\x05error\x18\x01 \x01(\v2\x14.core.v1.ErrorDetailR\x05error\"^\n" +
	"\vErrorDetail\x12\x1b\n" +
	"\tgrpc_code\x18\x01 \x01(\x05R\bgrpcCode\x122\n" +
	"\adetails\x18\x02 \x03(\v2\x18.core.v1.ErrorDetailInfoR\adetails\"=\n" +
	"\x0fErrorDetailInfo\x12*\n" +
	"\x06detail\x18\x01 \x01(\v2\x12.core.v1.ErrorInfoR\x06detail\"9\n" +
	"\tErrorInfo\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\" \n" +
	"\n" +
	"PathPrefix\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path:l\n" +
	"\x12service_descriptor\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\v2\x1a.core.v1.ServiceDescriptorR\x11serviceDescriptor:M\n" +
	"\x11method_descriptor\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\tR\x10methodDescriptor:P\n" +
	"\x12message_descriptor\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\tR\x11messageDescriptor:J\n" +
	"\x10field_descriptor\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\tR\x0ffieldDescriptorB\x9b\x01\n" +
	"\vcom.core.v1B\x10AnnotationsProtoP\x01Z=github.com/muhammadchandra19/exchange/proto/go/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_annotations_proto_rawDescOnce sync.Once
	file_core_v1_annotations_proto_rawDescData []byte
)

func file_core_v1_annotations_proto_rawDescGZIP() []byte {
	file_core_v1_annotations_proto_rawDescOnce.Do(func() {
		file_core_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_annotations_proto_rawDesc), len(file_core_v1_annotations_proto_rawDesc)))
	})
	return file_core_v1_annotations_proto_rawDescData
}

var file_core_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_v1_annotations_proto_goTypes = []any{
	(*ServiceDescriptor)(nil),           // 0: core.v1.ServiceDescriptor
	(*ErrorExample)(nil),                // 1: core.v1.ErrorExample
	(*ErrorDetail)(nil),                 // 2: core.v1.ErrorDetail
	(*ErrorDetailInfo)(nil),             // 3: core.v1.ErrorDetailInfo
	(*ErrorInfo)(nil),                   // 4: core.v1.ErrorInfo
	(*PathPrefix)(nil),                  // 5: core.v1.PathPrefix
	(*descriptorpb.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 7: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 8: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 9: google.protobuf.FieldOptions
}
var file_core_v1_annotations_proto_depIdxs = []int32{
	1,  // 0: core.v1.ServiceDescriptor.error_examples:type_name -> core.v1.ErrorExample
	5,  // 1: core.v1.ServiceDescriptor.path_prefixes:type_name -> core.v1.PathPrefix
	2,  // 2: core.v1.ErrorExample.error:type_name -> core.v1.ErrorDetail
	3,  // 3: core.v1.ErrorDetail.details:type_name -> core.v1.ErrorDetailInfo
	4,  // 4: core.v1.ErrorDetailInfo.detail:type_name -> core.v1.ErrorInfo
	6,  // 5: core.v1.service_descriptor:extendee -> google.protobuf.ServiceOptions
	7,  // 6: core.v1.method_descriptor:extendee -> google.protobuf.MethodOptions
	8,  // 7: core.v1.message_descriptor:extendee -> google.protobuf.MessageOptions
	9,  // 8: core.v1.field_descriptor:extendee -> google.protobuf.FieldOptions
	0,  // 9: core.v1.service_descriptor:type_name -> core.v1.ServiceDescriptor
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	9,  // [9:10] is the sub-list for extension type_name
	5,  // [5:9] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_core_v1_annotations_proto_init() }
func file_core_v1_annotations_proto_init() {
	if File_core_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_annotations_proto_rawDesc), len(file_core_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_annotations_proto_goTypes,
		DependencyIndexes: file_core_v1_annotations_proto_depIdxs,
		MessageInfos:      file_core_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_core_v1_annotations_proto_extTypes,
	}.Build()
	File_core_v1_annotations_proto = out.File
	file_core_v1_annotations_proto_goTypes = nil
	file_core_v1_annotations_proto_depIdxs = nil
}
