// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/v1/error.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED     ErrorCode = 0
	ErrorCode_ERROR_CODE_TIMEOUT         ErrorCode = 1
	ErrorCode_ERROR_CODE_FORBIDDEN       ErrorCode = 2
	ErrorCode_ERROR_CODE_UNAUTHORIZED    ErrorCode = 3
	ErrorCode_ERROR_CODE_SERVER_ERROR    ErrorCode = 4
	ErrorCode_ERROR_CODE_NOT_FOUND       ErrorCode = 5
	ErrorCode_ERROR_CODE_INVALID_REQUEST ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_TIMEOUT",
		2: "ERROR_CODE_FORBIDDEN",
		3: "ERROR_CODE_UNAUTHORIZED",
		4: "ERROR_CODE_SERVER_ERROR",
		5: "ERROR_CODE_NOT_FOUND",
		6: "ERROR_CODE_INVALID_REQUEST",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":     0,
		"ERROR_CODE_TIMEOUT":         1,
		"ERROR_CODE_FORBIDDEN":       2,
		"ERROR_CODE_UNAUTHORIZED":    3,
		"ERROR_CODE_SERVER_ERROR":    4,
		"ERROR_CODE_NOT_FOUND":       5,
		"ERROR_CODE_INVALID_REQUEST": 6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_core_v1_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_error_proto_rawDescGZIP(), []int{0}
}

// Standard error response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_core_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ErrorResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_core_v1_error_proto protoreflect.FileDescriptor

const file_core_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x13core/v1/error.proto\x12\acore.v1\"\x94\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId*\xcd\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x02\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x03\x12\x1b\n" +
	"\x17ERROR_CODE_SERVER_ERROR\x10\x04\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x05\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x06B\x95\x01\n" +
	"\vcom.core.v1B\n" +
	"ErrorProtoP\x01Z=github.com/muhammadchandra19/exchange/proto/go/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_error_proto_rawDescOnce sync.Once
	file_core_v1_error_proto_rawDescData []byte
)

func file_core_v1_error_proto_rawDescGZIP() []byte {
	file_core_v1_error_proto_rawDescOnce.Do(func() {
		file_core_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_error_proto_rawDesc), len(file_core_v1_error_proto_rawDesc)))
	})
	return file_core_v1_error_proto_rawDescData
}

var file_core_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_v1_error_proto_goTypes = []any{
	(ErrorCode)(0),        // 0: core.v1.ErrorCode
	(*ErrorResponse)(nil), // 1: core.v1.ErrorResponse
}
var file_core_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_error_proto_init() }
func file_core_v1_error_proto_init() {
	if File_core_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_error_proto_rawDesc), len(file_core_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_error_proto_goTypes,
		DependencyIndexes: file_core_v1_error_proto_depIdxs,
		EnumInfos:         file_core_v1_error_proto_enumTypes,
		MessageInfos:      file_core_v1_error_proto_msgTypes,
	}.Build()
	File_core_v1_error_proto = out.File
	file_core_v1_error_proto_goTypes = nil
	file_core_v1_error_proto_depIdxs = nil
}
