// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,import_extension=none"
// @generated from file kafka/v1/match.proto (package kafka.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kafka/v1/match.proto.
 */
export const file_kafka_v1_match: GenFile = /*@__PURE__*/
  fileDesc("ChRrYWZrYS92MS9tYXRjaC5wcm90bxIIa2Fma2EudjEi5gEKEU1hdGNoRXZlbnRQYXlsb2FkEhkKCG1hdGNoX2lkGAEgASgJUgdtYXRjaElEEi0KCXRpbWVzdGFtcBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDgoGc3ltYm9sGAMgASgJEg0KBXByaWNlGAQgASgBEg4KBnZvbHVtZRgFIAEoARIgCgxidXlfb3JkZXJfaWQYBiABKAlSCmJ1eU9yZGVySUQSIgoNc2VsbF9vcmRlcl9pZBgHIAEoCVILc2VsbE9yZGVySUQSEgoKdGFrZXJfc2lkZRgIIAEoCUKcAQoMY29tLmthZmthLnYxQgpNYXRjaFByb3RvUAFaP2dpdGh1Yi5jb20vbXVoYW1tYWRjaGFuZHJhMTkvZXhjaGFuZ2UvcHJvdG8vZ28va2Fma2EvdjE7a2Fma2F2MaICA0tYWKoCCEthZmthLlYxygIIS2Fma2FcVjHiAhRLYWZrYVxWMVxHUEJNZXRhZGF0YeoCCUthZmthOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message kafka.v1.MatchEventPayload
 */
export type MatchEventPayload = Message<"kafka.v1.MatchEventPayload"> & {
  /**
   * @generated from field: string match_id = 1 [json_name = "matchID"];
   */
  matchId: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 2;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string symbol = 3;
   */
  symbol: string;

  /**
   * @generated from field: double price = 4;
   */
  price: number;

  /**
   * @generated from field: double volume = 5;
   */
  volume: number;

  /**
   * @generated from field: string buy_order_id = 6 [json_name = "buyOrderID"];
   */
  buyOrderId: string;

  /**
   * @generated from field: string sell_order_id = 7 [json_name = "sellOrderID"];
   */
  sellOrderId: string;

  /**
   * @generated from field: string taker_side = 8;
   */
  takerSide: string;
};

/**
 * Describes the message kafka.v1.MatchEventPayload.
 * Use `create(MatchEventPayloadSchema)` to create a new message.
 */
export const MatchEventPayloadSchema: GenMessage<MatchEventPayload> = /*@__PURE__*/
  messageDesc(file_kafka_v1_match, 0);

