// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,import_extension=none"
// @generated from file kafka/v1/order.proto (package kafka.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kafka/v1/order.proto.
 */
export const file_kafka_v1_order: GenFile = /*@__PURE__*/
  fileDesc("ChRrYWZrYS92MS9vcmRlci5wcm90bxIIa2Fma2EudjEijwEKEVBsYWNlT3JkZXJQYXlsb2FkEhkKCG9yZGVyX2lkGAEgASgJUgdvcmRlcklEEhcKB3VzZXJfaWQYAiABKAlSBnVzZXJJRBIMCgR0eXBlGAMgASgJEgsKA2JpZBgEIAEoCBIMCgRzaXplGAUgASgBEg0KBXByaWNlGAYgASgBEg4KBm9mZnNldBgHIAEoA0KcAQoMY29tLmthZmthLnYxQgpPcmRlclByb3RvUAFaP2dpdGh1Yi5jb20vbXVoYW1tYWRjaGFuZHJhMTkvZXhjaGFuZ2UvcHJvdG8vZ28va2Fma2EvdjE7a2Fma2F2MaICA0tYWKoCCEthZmthLlYxygIIS2Fma2FcVjHiAhRLYWZrYVxWMVxHUEJNZXRhZGF0YeoCCUthZmthOjpWMWIGcHJvdG8z");

/**
 * @generated from message kafka.v1.PlaceOrderPayload
 */
export type PlaceOrderPayload = Message<"kafka.v1.PlaceOrderPayload"> & {
  /**
   * @generated from field: string order_id = 1 [json_name = "orderID"];
   */
  orderId: string;

  /**
   * @generated from field: string user_id = 2 [json_name = "userID"];
   */
  userId: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: bool bid = 4;
   */
  bid: boolean;

  /**
   * @generated from field: double size = 5;
   */
  size: number;

  /**
   * @generated from field: double price = 6;
   */
  price: number;

  /**
   * @generated from field: int64 offset = 7;
   */
  offset: bigint;
};

/**
 * Describes the message kafka.v1.PlaceOrderPayload.
 * Use `create(PlaceOrderPayloadSchema)` to create a new message.
 */
export const PlaceOrderPayloadSchema: GenMessage<PlaceOrderPayload> = /*@__PURE__*/
  messageDesc(file_kafka_v1_order, 0);

