// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,import_extension=none"
// @generated from file core/v1/error.proto (package core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file core/v1/error.proto.
 */
export const file_core_v1_error: GenFile = /*@__PURE__*/
  fileDesc("ChNjb3JlL3YxL2Vycm9yLnByb3RvEgdjb3JlLnYxImYKDUVycm9yUmVzcG9uc2USDAoEY29kZRgBIAEoCRIPCgdtZXNzYWdlGAIgASgJEg8KB2RldGFpbHMYAyABKAkSEQoJdGltZXN0YW1wGAQgASgDEhIKCnJlcXVlc3RfaWQYBSABKAkqzQEKCUVycm9yQ29kZRIaChZFUlJPUl9DT0RFX1VOU1BFQ0lGSUVEEAASFgoSRVJST1JfQ09ERV9USU1FT1VUEAESGAoURVJST1JfQ09ERV9GT1JCSURERU4QAhIbChdFUlJPUl9DT0RFX1VOQVVUSE9SSVpFRBADEhsKF0VSUk9SX0NPREVfU0VSVkVSX0VSUk9SEAQSGAoURVJST1JfQ09ERV9OT1RfRk9VTkQQBRIeChpFUlJPUl9DT0RFX0lOVkFMSURfUkVRVUVTVBAGQpUBCgtjb20uY29yZS52MUIKRXJyb3JQcm90b1ABWj1naXRodWIuY29tL211aGFtbWFkY2hhbmRyYTE5L2V4Y2hhbmdlL3Byb3RvL2dvL2NvcmUvdjE7Y29yZXYxogIDQ1hYqgIHQ29yZS5WMcoCB0NvcmVcVjHiAhNDb3JlXFYxXEdQQk1ldGFkYXRh6gIIQ29yZTo6VjFiBnByb3RvMw");

/**
 * Standard error response
 *
 * @generated from message core.v1.ErrorResponse
 */
export type ErrorResponse = Message<"core.v1.ErrorResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string details = 3;
   */
  details: string;

  /**
   * @generated from field: int64 timestamp = 4;
   */
  timestamp: bigint;

  /**
   * @generated from field: string request_id = 5;
   */
  requestId: string;
};

/**
 * Describes the message core.v1.ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/
  messageDesc(file_core_v1_error, 0);

/**
 * Error codes
 *
 * @generated from enum core.v1.ErrorCode
 */
export enum ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_CODE_TIMEOUT = 1;
   */
  TIMEOUT = 1,

  /**
   * @generated from enum value: ERROR_CODE_FORBIDDEN = 2;
   */
  FORBIDDEN = 2,

  /**
   * @generated from enum value: ERROR_CODE_UNAUTHORIZED = 3;
   */
  UNAUTHORIZED = 3,

  /**
   * @generated from enum value: ERROR_CODE_SERVER_ERROR = 4;
   */
  SERVER_ERROR = 4,

  /**
   * @generated from enum value: ERROR_CODE_NOT_FOUND = 5;
   */
  NOT_FOUND = 5,

  /**
   * @generated from enum value: ERROR_CODE_INVALID_REQUEST = 6;
   */
  INVALID_REQUEST = 6,
}

/**
 * Describes the enum core.v1.ErrorCode.
 */
export const ErrorCodeSchema: GenEnum<ErrorCode> = /*@__PURE__*/
  enumDesc(file_core_v1_error, 0);

