// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,import_extension=none"
// @generated from file core/v1/response.proto (package core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file core/v1/response.proto.
 */
export const file_core_v1_response: GenFile = /*@__PURE__*/
  fileDesc("ChZjb3JlL3YxL3Jlc3BvbnNlLnByb3RvEgdjb3JlLnYxIsMBCgtBcGlSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSIgoEZGF0YRgDIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSLQoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBISCgpyZXF1ZXN0X2lkGAUgASgJEisKCG1ldGFkYXRhGAYgASgLMhkuY29yZS52MS5SZXNwb25zZU1ldGFkYXRhIoIBChBSZXNwb25zZU1ldGFkYXRhEhMKC3RvdGFsX2NvdW50GAEgASgFEhEKCXBhZ2Vfc2l6ZRgCIAEoBRIUCgxjdXJyZW50X3BhZ2UYAyABKAUSFQoNaGFzX25leHRfcGFnZRgEIAEoCBIZChFoYXNfcHJldmlvdXNfcGFnZRgFIAEoCCJZChFQYWdpbmF0aW9uUmVxdWVzdBIMCgRwYWdlGAEgASgFEhEKCXBhZ2Vfc2l6ZRgCIAEoBRIPCgdzb3J0X2J5GAMgASgJEhIKCnNvcnRfb3JkZXIYBCABKAlCmAEKC2NvbS5jb3JlLnYxQg1SZXNwb25zZVByb3RvUAFaPWdpdGh1Yi5jb20vbXVoYW1tYWRjaGFuZHJhMTkvZXhjaGFuZ2UvcHJvdG8vZ28vY29yZS92MTtjb3JldjGiAgNDWFiqAgdDb3JlLlYxygIHQ29yZVxWMeICE0NvcmVcVjFcR1BCTWV0YWRhdGHqAghDb3JlOjpWMWIGcHJvdG8z", [file_google_protobuf_any, file_google_protobuf_timestamp]);

/**
 * Standard API response wrapper
 *
 * @generated from message core.v1.ApiResponse
 */
export type ApiResponse = Message<"core.v1.ApiResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: google.protobuf.Any data = 3;
   */
  data?: Any;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string request_id = 5;
   */
  requestId: string;

  /**
   * @generated from field: core.v1.ResponseMetadata metadata = 6;
   */
  metadata?: ResponseMetadata;
};

/**
 * Describes the message core.v1.ApiResponse.
 * Use `create(ApiResponseSchema)` to create a new message.
 */
export const ApiResponseSchema: GenMessage<ApiResponse> = /*@__PURE__*/
  messageDesc(file_core_v1_response, 0);

/**
 * Response metadata
 *
 * @generated from message core.v1.ResponseMetadata
 */
export type ResponseMetadata = Message<"core.v1.ResponseMetadata"> & {
  /**
   * @generated from field: int32 total_count = 1;
   */
  totalCount: number;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: int32 current_page = 3;
   */
  currentPage: number;

  /**
   * @generated from field: bool has_next_page = 4;
   */
  hasNextPage: boolean;

  /**
   * @generated from field: bool has_previous_page = 5;
   */
  hasPreviousPage: boolean;
};

/**
 * Describes the message core.v1.ResponseMetadata.
 * Use `create(ResponseMetadataSchema)` to create a new message.
 */
export const ResponseMetadataSchema: GenMessage<ResponseMetadata> = /*@__PURE__*/
  messageDesc(file_core_v1_response, 1);

/**
 * Pagination request
 *
 * @generated from message core.v1.PaginationRequest
 */
export type PaginationRequest = Message<"core.v1.PaginationRequest"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string sort_by = 3;
   */
  sortBy: string;

  /**
   * "asc" or "desc"
   *
   * @generated from field: string sort_order = 4;
   */
  sortOrder: string;
};

/**
 * Describes the message core.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_core_v1_response, 2);

